Debug: false

server:
  #address: 0.0.0.0
  port: 9999
  servlet:
    context-path: /agm-rs
  ssl:
    enabled: false
    protocol: TLS
    key-store-type: PKCS12
    key-store: classpath:keystore/agm-uat.intra.acer.com.pfx
    key-store-password: xxxxxx
    #key-store: ${user.home}/agm-rs/conf/aap.agbs-uat.acer.com-with-chain.pfx
  #error:
    #include-exception: true
    #include-stacktrace: always  
  
spring:
  main:
    banner-mode: console
  banner:
    location: banner.txt  
  application:
    name: agm-rs
    admin:
      enabled: true    
  undertow:
    accesslog:
      enabled: true
      dir: log  
  datasource:
    url: jdbc:oracle:thin:@//twtpedb01u.hq.intra.acer.com:1521/AGBSITQA
    username: AGBS
    password: agbsTWitqa1
    #url: jdbc:h2:mem:testdb
    #username: sa
    #password: 
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: AgmRsHikariCP
      maximumPoolSize: 50
      minimumIdle: 5
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000
      autoCommit: false
  jpa:
    open-in-view: true
  cache:
#    type: ehcache
    jcache:
      config: classpath:ehcache.xml 
  devtools:
    add-properties: true
    livereload:
      enabled: true
      port: 35729
#    remote:
#      restart:
#        enabled: false
#      secret:
#      secret-header-name: X-AUTH-TOKEN
#      context-path: /.~~spring-boot!~
#      proxy:
#        host:
#        port:
    restart:
      enabled: true
      exclude: META-INF/maven/**,META-INF/resources/**,resources/**,static/**,public/**,templates/**,**/*Test.class,**/*Tests.class,git.properties,META-INF/build-info.properties
      additional-exclude:
      trigger-file:
      additional-paths:
      log-condition-evaluation-delta: true
      poll-interval: 1s
      quiet-period: 400ms
      
#mybatis:
#  type-aliases-package: tw.com.agm.rs.model
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml      
      
management:
  health:
    probes: 
      enabled: ture
  endpoints:
    web:
      exposure:
        include: ["*"]
  metrics:
    tags:
      application: ${spring.application.name}
      region: my-region